name: React Build and Upload

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Set Up SSH Private Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/id_rsa.pem
          chmod 600 /tmp/id_rsa.pem

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd public
          npm install

      - name: Debug - List Project Directory
        run: pwd && ls

      - name: Build React App
        run: |
          cd public
          npm run build

      - name: Upload Build to Server
        run: |
          scp -o StrictHostKeyChecking=no -i /tmp/id_rsa.pem -r public/build/* ubuntu@13.235.83.187:/home/ubuntu/ridham-app/

      - name: Clean Up SSH Private Key
        run: rm /tmp/id_rsa.pem